### ISSUE TITLE
Eliminating the centralization of powers

### ISSUE THREAD

**Issue by tonilanec** [Bit-Nation/BITNATION-Constitution#21]
We have a responsibility to ensure the centralization of powers does not propagate through our system. It is our collective duty to ensure we have a statement in the constitution preventing centralized power, centralized force and centralized coercion.

**Comment by Whytehorse** [comment]
Issue resolved with patch https://github.com/Whytehorse/American-Revolution-Constitution/pull/1

Please merge and close this issue

**Comment by Whytehorse** [comment]
My patch had to be rolled back. This is still unresolved
